[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build]
  command = "npm run build  && netlify-lambda build src/lambda"
  publish = "dist"
  functions = "./functions"

[dev]
  command = "npm run start"
  port = 8888
  targetPort = 8080
  publish= "site/build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
